In [2]:
import numpy as np
import time

In [3]:
#create - from list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [4]:
#create
arr1 = np.zeros((2, 3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((5, 4), 100) #prefill will val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 10, 2) #identity matrix
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #identity matrix
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (5, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  1.  34.  67. 100.] (4,)


In [7]:
#properties
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [9]:
#operation on arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr, arr.shape)

reshaped = arr.reshape((3, 2))
print(reshaped, reshaped.shape)

flattened = arr.flatten() #2D -> 1D
print(flattened, flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [13]:
#Indexing

# arr = np.array([1, 2, 3, 4, 5])

# print(arr[0])
# print(arr[3])

# arr = np.array([[1, 2, 3], [4, 5, 6]])
# print(arr[0][2])
# print(arr[1][1])

#fancy Indexing
# arr = np.array([1, 2, 3, 4, 5])
# idx = [0, 1, 3]
# print(arr[idx])

#Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])


[3 4 5]
[2 4]
[1 3 5]


In [16]:
#Slicing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[:])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 2 3 4 5]
[1 3 5]


In [21]:
#Copy vs View
#For normal list
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

#For NumPy list
arr = np.array([1, 2, 3, 4, 5])
# sub_arr = arr[1:3]
sub_arr = arr[1:3].copy()
print(sub_arr)
sub_arr[0] = 200

print(sub_arr)
print(arr)

[2 3]
[200   3]
[1 2 3 4 5]


In [28]:
#Data type
# arr = np.array([1, 2, 3.14, 4, 5, "prime"])
# print(arr, arr.dtype)
# arr1 = np.array([3 + 5j])
# arr2 = np.array([2 + 3j])
# print(arr1 + arr2)
# print(arr1 - arr2)
arr = np.array(["prime", {1, 2, 3}, 3.14])
print(arr, arr.dtype)


['prime' {1, 2, 3} 3.14] object


In [32]:
#Multi-dimensional array

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2D)
print(np.sum(arr2D))

sum_of_cols = np.sum(arr2D, axis = 0)
print(sum_of_cols)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [39]:
#3D array
arr3D = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]]]) #2 x 3 x 2
print(arr3D, arr3D.shape)

#Indexing
print(arr3D[0, 1, 1])
print(arr3D[1, 1, 0])

#slicing
print(arr3D[:, 0, :]) #1st row from both layers
print(arr3D[:, :, 0]) #1st row from both layers
arr3D[:, :, 0] = 99
print(arr3D)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]


In [42]:
#Vectorization
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
print(arr1 ** 2)
print(arr1 + 10)
print(arr1 + arr2)

[ 1  4  9 16 25]
[11 12 13 14 15]
[ 7  9 11 13 15]


In [47]:
#Broadcasting
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

# ValueError: operands could not be broadcast together with shapes (3,5) (2,5)
print(arr1.shape)
print(arr2.shape)

print(arr1 + arr2)


(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [53]:
#Normalize
arr = np.array([[1, 2], [3, 4]])
mean = np.mean(arr)
std_dev = np.std(arr)

normalized_arr = (arr-mean)/std_dev
print(normalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [62]:
#Mathematical fnx

#aggregation
arr = np.array([1, 2, 3, 4, 5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))


15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [63]:
#Power
arr = np.array([1, 2, 3, 4, 5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr, 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [65]:
#Log & Exponential
arr = np.array([1, 2, 3, 4, 5])

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [68]:
#Rounding value
print(np.round(3.94))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

4.0
4.0
3.0
3.0
