In [6]:
import numpy as np
import time

In [22]:
#create - from list
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.shape)

arr2 = np.array([1, 2, 3, 4, 5, "prime"])
print(arr2, type(arr2), arr2.dtype, arr2.shape)

arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2D, arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [35]:
#create
arr1 = np.zeros((2, 3), dtype = "int64") #prefill
print(arr1, arr1.shape)

arr2 = np.ones((5, )) #prefill
print(arr2, arr2.shape)

arr3 = np.full((5, 4), 100) #prefill will val
print(arr3, arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4, arr4.shape)

arr5 = np.arange(0, 10, 2) #identity matrix
print(arr5, arr5.shape)

arr6 = np.linspace(1, 100, 4) #identity matrix
print(arr6, arr6.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[1. 1. 1. 1. 1.] (5,)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (5, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[0 2 4 6 8] (5,)
[  1.  34.  67. 100.] (4,)
